### ISSUE TITLE
increase batch size (or make it command-dependent)

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept-cli#15]
maybe also make this a secret command line option

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/15) by @silox on Tue Mar 31 2015 at 11:22._
_Closed by @bmesuere on Thu Jun 18 2015 at 11:00._

**Comment by bmesuere** [comment]
There's no limit, but the database query is batched.


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-15449) by @bmesuere on Wed Apr 01 2015 at 14:33._

**Comment by bmesuere** [comment]
The batch size already can be made command depended by overwriting the `batch_size` function in the commands themselves.

Would it be interesting to add a parameter so the user himself can change the `batch_size` (perhaps with a warning)? I added this locally for benchmarking purposes already so I can make a PR out of this is this is wanted.


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-16023) by @silox on Wed Apr 15 2015 at 09:41._

**Comment by bmesuere** [comment]
Pushed it in a seperate branch: https://github.ugent.be/unipept/unipept-cli/commit/1b4f82476958a5fa99d884664e035e1f08273b28


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-16025) by @silox on Wed Apr 15 2015 at 09:56._

**Comment by bmesuere** [comment]
I wouldn't expose this to the user since he know nothing about the internals of the cli and server. We can add it, but keep it secret i.e. not add it to the help and docs.


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-16027) by @bmesuere on Wed Apr 15 2015 at 10:05._

**Comment by bmesuere** [comment]
cri doesn't yet allow for options to be made hidden; I created an issue here: https://github.com/ddfreyne/cri/issues/43


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-16030) by @silox on Wed Apr 15 2015 at 11:00._

**Comment by bmesuere** [comment]
Hidden options were added to cri. I suggest using these default values:
- pept2prot: 10 (or 5?, or 5 with extra options?)
- pept2taxa: 10?
- pept2lca: 1000, but maybe less when extra options are requested?


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-16449) by @bmesuere on Wed Apr 22 2015 at 14:05._

**Comment by pdawyndt** [comment]
I would recommend to give pept2prot and pept2taxa the same defaults, since both possibly return multiple output lines; pept2lca can indeed be given a different size since there's only one output line; Tom's test seem to indicate that 1000 currently is a sensible default


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-16514) by @pdawyndt on Thu Apr 23 2015 at 15:41._

**Comment by bmesuere** [comment]
I used these values:
- pept2prot and pept2taxa: default 10, with --extra 5
- pept2lca: default 1000, with --extra 100
- taxonomy: 100


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-18460) by @bmesuere on Tue Jun 09 2015 at 19:25._

**Comment by bmesuere** [comment]
implemented in #38 and #35 


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/15#issuecomment-18608) by @bmesuere on Thu Jun 18 2015 at 11:00._
