### ISSUE TITLE
option -s should generate an error message for non-existing fields

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept-cli#16]
If the argument passed to the `-s` option contains a non-existing field, the command should generate an error message (or a warning) instead of silently skipping this option.

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/16) by @pdawyndt on Wed Apr 01 2015 at 21:42._

**Comment by bmesuere** [comment]
this is a filter on the output, so we can't check beforehand if the flags are valid. In addition, we support wildcards, so a check won't be easy in the first place.
