### ISSUE TITLE
CLI sends fasta headers to the server when the fasta header is the last entry in a batch

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept-cli#17]
Input gets split up into batches. While iterating over a batch from a fastafile, a hash (`fasta_mapper`) is computed by mapping each peptide to its fasta header (or headers in #12). Afterwards, the values of this hash gets substracted from the input, yielding only the peptides without fasta headers.

This however doesn't work in the case when the fasta header is the last entry in a batch. For example:

Batch:

```
>|ABO10505.2
LNFSAEDK
MLTTQNGTNYEVVGIVQIGLAYLFVR
MMEEWALAAK
NLNSIEK
QGVYDATMMSVLK
QLPQNFAMVK
SGESYK
SWQADITLIPFQDEALVDR
TNFECTLTGE
>|ABO10506.2
```

`fasta_mapper`:

```
{"LNFSAEDK"=>">|ABO10505.2", "MLTTQNGTNYEVVGIVQIGLAYLFVR"=>">|ABO10505.2", "MMEEWALAAK"=>">|ABO10505.2", "NLNSIEK"=>">|ABO10505.2", "QGVYDATMMSVLK"=>">|ABO10505.2", "QLPQNFAMVK"=>">|ABO10505.2", "SGESYK"=>">|ABO10505.2", "SWQADITLIPFQDEALVDR"=>">|ABO10505.2", "TNFECTLTGE"=>">|ABO10505.2"}
```

Batch after substracting the values from the batch:

```
LNFSAEDK
MLTTQNGTNYEVVGIVQIGLAYLFVR
MMEEWALAAK
NLNSIEK
QGVYDATMMSVLK
QLPQNFAMVK
SGESYK
SWQADITLIPFQDEALVDR
TNFECTLTGE
>|ABO10506.2
```

The `>|ABO10506.2` isn't subtracted as there is no peptide in the batch corresponding to this fasta header.

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/17) by @silox on Sun Apr 05 2015 at 12:14._
_Closed by @silox on Wed Apr 08 2015 at 18:17._

**Comment by bmesuere** [comment]
I see two possible solutions here:
1. Keeping a set of fasta headers when iterating and removing this set from the batch input (using `batch -= set`)
2. Delete a fasta header immediately from the input when we find one (using `batch.delete_at index`)

1 uses a bit more memory, while 2 could be slower as we delete multiple times from an array while 1 only does it once


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/17#issuecomment-15663) by @silox on Sun Apr 05 2015 at 12:36._

**Comment by bmesuere** [comment]
I'll go for option 1: the maximum amount of extra memory is batch_size*string_size, which isn't a lot. `delete_at` would shift the input array after the deleted element every time we delete a fasta header from the input


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/17#issuecomment-15664) by @silox on Sun Apr 05 2015 at 12:44._

**Comment by pdawyndt** [comment]
@silox have you been able to get rid of the performance penalty? Have you done a timing comparison between the new and the old version, to see if the new version doens't have any remaining performance penalties?


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/17#issuecomment-15781) by @pdawyndt on Wed Apr 08 2015 at 19:09._

**Comment by bmesuere** [comment]
@pdawyndt Yes: The bad performance was caused by the code I wrote to determine the index of a fasta header, but I completely rewrote it to work with a queue-like implementation. There should be a very tiny performance hit (because we keep a dictionary of `peptide => [fasta_headers]` instead of `peptide => fasta_header` now) but it isn't signifcant as can be seen in these quick benchmarks:

#### BATCH SIZE 10000

##### Master

```
cat /tmp/GCF_000015425.1/peptides.fst  0.00s user 0.01s system 0% cpu 0.959 total
unipept pept2lca > before_everything  3.27s user 0.42s system 32% cpu 11.289 total
```

##### Fixed - without optimizations

```
cat peptides.fst  0.00s user 0.00s system 0% cpu 0.938 total
unipept pept2lca > without_opts  660.29s user 6.60s system 96% cpu 11:33.71 total
```

##### Fixed - with optimizations

```
cat peptides.fst  0.00s user 0.01s system 0% cpu 1.181 total
unipept pept2lca > after_fix  3.44s user 0.35s system 62% cpu 6.068 total
```

#### BATCH SIZE 100

##### Master

```
cat /tmp/GCF_000015425.1/peptides.fst  0.00s user 0.00s system 0% cpu 6.717 total
unipept pept2lca > before_everything  4.44s user 0.42s system 60% cpu 7.977 total
```

##### Fixed - without optimizations

```
cat /tmp/GCF_000015425.1/peptides.fst  0.00s user 0.00s system 0% cpu 9.707 total
unipept pept2lca > without_opts  8.86s user 0.33s system 79% cpu 11.573 total
```

##### Fixed - with optimizations

```
cat /tmp/GCF_000015425.1/peptides.fst  0.00s user 0.00s system 0% cpu 6.625 total
unipept pept2lca > after_fix  4.64s user 0.38s system 63% cpu 7.866 total
```

There even is an approach which uses less memory: We could keep a dictionary of `index_number` on `fasta_header` in a batch. Something like `{1 => Header1, 7 => Header2}` for each batch. In the printing step, we could enumerate over the results and check which header we need to print based on the enumeration index. It is however not possible to implement this yet: Peptides without a matching LCA don't end up in the results, so the enumeration would not correspond to the indexes used in the dictionary. 
I think there were plans to include non-found peptides in the results, so when this addition is made, the approach described above would be possible and would maybe even fix the memleak.


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/17#issuecomment-15782) by @silox on Wed Apr 08 2015 at 19:33._

**Comment by pdawyndt** [comment]
@silox do we have a clear idea what is causing the memory leak; would be good if we could trace what's causing it


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/17#issuecomment-15799) by @pdawyndt on Thu Apr 09 2015 at 08:58._
