### ISSUE TITLE
New line in the peptide column in unipept pept2lca with input file

### ISSUE THREAD

**Issue by dwishsan** [unipept/unipept-cli#182]
Hello,

Thank you for unipept :)

Running the [unipept pept2lca exemples](https://unipept.ugent.be/clidocs/pept2lca), I did not get the expected results:
```shell
$ more input2.txt
AALTER
MDGTEYIIVK
$ unipept pept2lca --input input2.txt
peptide,taxon_id,taxon_name,taxon_rank
"AALTER
",1,root,no rank
MDGTEYIIVK,572511,Blautia,genus
``` 

The `\n` character is not stripped from the first peptide.

Unipept version:
``` shell
$ unipept --version
3.1.0
``` 

Best,
Audric

**Comment by pverscha** [comment]
Hi @dwishsan,

Thank you for contacting us. We have made some server-side changes and the issue should be resolved now. If you're still experiencing problems, feel free to contact us again.
