### ISSUE TITLE
unipept command does not properly combine option letters

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept-cli#25]
The UniPept CLI does not properly combine options if the last option has a required argument. The following two command lines are expected to give the same outcome.

``` bash
$ unipept taxonomy -a -s phylum_name 35493
phylum_name
Streptophyta
$ unipept taxonomy -as phylum_name 35493
taxonomy: option requires an argument -- s
```

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/25) by @pdawyndt on Thu Apr 23 2015 at 15:32._

**Comment by bmesuere** [comment]
This is a cri issue, reported at https://github.com/ddfreyne/cri/issues/46


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/25#issuecomment-16907) by @bmesuere on Fri May 01 2015 at 11:06._

**Comment by bmesuere** [comment]
This has been fixed in cri.


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/25#issuecomment-46612) by @bmesuere on Mon Jun 26 2017 at 14:46._

**Comment by bmesuere** [comment]
this was fixed a long time ago
