### ISSUE TITLE
some CLI commands should not expect subcommands

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept-cli#46]
The `peptfilter` command has a weird error message if peptides are passed as arguments:

```
$ peptfilter ABC DEFJEFEJE
peptfilter: unknown command 'ABC'
```

It gives the impression that the command expects subcommands.

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/46) by @pdawyndt on Fri Jul 10 2015 at 15:32._
_Closed by @bmesuere on Tue Jul 14 2015 at 18:02._

**Comment by bmesuere** [comment]
This seems like a bug in cri. 


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/46#issuecomment-19078) by @bmesuere on Tue Jul 14 2015 at 14:03._
