### ISSUE TITLE
Real FASTA output

### ISSUE THREAD

**Issue by ninewise** [unipept/unipept-cli#54]
(moved from https://github.ugent.be/unipept/unipept-metagenomics-scripts/issues/17)

At the moment we have FASTA in, CSV (with a FASTA column out) when one might expect a FASTA out file. 

Now:

```
[10:17] silox`@Gallifrey` ~/Documents/Projects ✔ unipept pept2prot -i test.fst 
fasta_header,peptide,uniprot_id,taxon_id
>a|1,IITHPNFNGNTLDNDIMLIK,P00761,9823
>a|1,IITHPNFNGNTLDNDIMLIK,F1SRS2,9823
>a|1,IITHPNFNGNTLDNDIMLIK,C5IWV5,9823
>b|2,IITHPNFNGNTLDNDIMLIK,P00761,9823
>b|2,IITHPNFNGNTLDNDIMLIK,F1SRS2,9823
>b|2,IITHPNFNGNTLDNDIMLIK,C5IWV5,9823
```

Later:

```
[10:17] silox`@Gallifrey` ~/Documents/Projects ✔ unipept pept2prot -i test.fst 
fasta_header,peptide,uniprot_id,taxon_id
>a|1
IITHPNFNGNTLDNDIMLIK,P00761,9823
IITHPNFNGNTLDNDIMLIK,F1SRS2,9823
IITHPNFNGNTLDNDIMLIK,C5IWV5,9823
>b|2
IITHPNFNGNTLDNDIMLIK,P00761,9823
IITHPNFNGNTLDNDIMLIK,F1SRS2,9823
IITHPNFNGNTLDNDIMLIK,C5IWV5,9823
```

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/54) by @ninewise on Fri Jun 15 2018 at 17:21._
_Closed by @ninewise on Sat Jun 16 2018 at 23:07._

**Comment by bmesuere** [comment]
no, this works as expected, the first format is valid csv and can be loaded into excel for example. The second format is something fasta-like that needs more postprocessing 

_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/54#issuecomment-77977) by @bmesuere on Sat Jun 16 2018 at 10:21._
