### ISSUE TITLE
Add more output options to the uniprot command

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept-cli#7]
The Uniprot website offers a list of export formats. These could be added as output formats to the uniprot command:
- TEXT: http://www.uniprot.org/uniprot/I8YV13.txt
- XML: http://www.uniprot.org/uniprot/I8YV13.xml
- RDF: http://www.uniprot.org/uniprot/I8YV13.rdf
- GFF: http://www.uniprot.org/uniprot/I8YV13.gff
- FASTA: http://www.uniprot.org/uniprot/I8YV13.fasta 

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/7) by @bmesuere on Sat Aug 16 2014 at 14:56._
_Closed by an unknown user on Wed Apr 22 2015 at 15:42._

**Comment by pdawyndt** [comment]
the `uniprot` command used to support the `-s` option, but this no longer seems the case; see [TPA case study](https://github.ugent.be/unipept/unipept-cli/wiki/case-TPA/_edit) for an example; could also be that this was a feature that I invented while writing Toon's thesis, but anyway it is a "nice to have" feature


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/7#issuecomment-15479) by @pdawyndt on Wed Apr 01 2015 at 21:50._
